In [4]:
import csv
import numpy as np

with open('matrix.txt', 'r') as f:
    matrix = np.array(list(csv.reader(f, delimiter=',')), dtype='int')

print(matrix)

[[4445 2697 5115 ... 2758 3748 5870]
 [1096   20 1318 ... 4187 9353 9377]
 [9607 7385  521 ... 9515 6385 9230]
 ...
 [2265 8192 1763 ... 7456 5128 5294]
 [2132 8992 8160 ... 5634 1113 5789]
 [5304 5499  564 ... 2751 3406 7981]]
